#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov 10 23:49:10 2018

@author: tb460
"""

import pandas as pd

class CountCalls:
    def __init__(self):
        self.counter = 0

    def your_function(self, window):
        retval = (window[3],sum(window))
        self.counter = self.counter + 1
        return window[3]
    
TestCounter = CountCalls()

my_series=pd.Series(range(100))

output = pd.Series.rolling(my_series, window = 5).apply(TestCounter.your_function)

print(TestCounter.counter)