#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  1 19:11:58 2018

@author: tb460
"""

# functions to compute standard EWS from time-series data

# smooth_function

def myfun(country="angleterre"):
    print("I am from",country)
    
